version: '3.8'

services:
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - mongo-network  
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo admin --quiet
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mongo-network:
    driver: bridge

volumes:
  dbdata:
  dblog: